apiVersion: v1
kind: Pod
metadata:
  name: main
  namespace: default
  labels:
    apps.kubernetes.io/instance: hello-world
spec:
  containers:
    - name: main
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - 1h
