apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: default
  labels:
    apps.kubernetes.io/instance: my-app
spec:
  containers:
    - name: main
      image: my-app:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
          hostPort: 8080
